# see https://docs.travis-ci.com/user/languages/scala/ for more hints
language: scala

# list any Scala version you want to test against
scala:
  - 2.12.2
jdk:
  - oraclejdk8

script:
  - ./build.sh executable

before_deploy:
  - zip /tmp/win_package.zip crypto.cmd encryption4s.jar README.md
  - printf '#!/usr/bin/env bash\nmv crypto /usr/local/bin/ ' > install_crypto.sh && chmod +x install_crypto.sh
  - printf '#!/usr/bin/env bash\nrm /usr/local/bin/crypto ' > uninstall_crypto.sh && chmod +x uninstall_crypto.sh
  - zip /tmp/package.zip crypto install_crypto.sh uninstall_crypto.sh README.md

deploy:
  provider: releases
  api_key:
    secure: uwL8jEnrpHBzV07ILqRLW6s7So1AWvOg76IBwo2MF+rk9oJN0JZvOjl5FqGiZiZ4i/guK0SyyP7A7lF+1mVZVTtwdRpNwt5TCkFc0dMPlp1Uk77RhmIfoE1Ma1XC/NlslMCZVgObYMAEFyviwSfkwW2OlfeVV2dFcv4K9PcJW7hjodstUqbV+yLMja6CkoFyv1qWG8ieA7eByil+No/W797k5/mGj88BNfqun6sYvaCg+jmO7xb5Hchv/rhSpExxVCETVVX+odHyGJz2LxEj5Ygs1bCvoezSnVH2d+ecAK/ZEdgUKdZk5W9fWkscmqX0VNCknONU2/h2Tn7eVrgwy/7shAQy1P4RRbHWT/1idEV4m6P8RHhgWU2QbvzkD9MKvAIaN7wheKdHLHPV12yEqPbg+ZnCKqxf3auFd+BY9bSvzv4LtZFwETAlpGNxpvW45I6qyk8gSB4fzt9m+E5x5ql32N0REip2+3N16bA2YqNJbZcMvuXQ0wrTPr2hZgBfyXqYdR6N88GJ8blUDHVKD7gMPqsJYxEUihzjWWM7xeWyiHexeW49dNWtPMqTpQoweY9J/GVIb3HD8uqNLuoNNVcdQsQqAx3xdbZW1KdZmJcDDaXkIEMpAUMUBuURIxFrox9A5NjUXv4XTGTSh9kFFfTMqz29So7xyQR2wB+sEDU=
  file:
    - /tmp/package.zip
    - /tmp/win_package.zip
  on:
    repo: onema/KmsEncryption4S
    tags: true
    all_branches: true
